global using System.Text.Json;
global using System.Text.Json.Serialization;
global using LibraryManagement.Api.ExceptionHandler;
global using LibraryManagement.Application.Dtos.Books;
global using LibraryManagement.Application.Dtos.Users;
global using LibraryManagement.Application.Services.Books;
global using LibraryManagement.Application.Services.Users;
global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Mvc;